const sovereignData = [
    {
        "name": "Aave",
        "type": "Protocol State",
        "space_id": "aave.eth",
        "population": 1040,
        "bills": 24,
        "health": 23.08,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x464c71f6c2f760dda36715fbc0833c5a7d9b2bb2",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Uniswap",
        "type": "Protocol State",
        "space_id": "uniswap.eth",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x1a9c8182c09f50c8318d769245beaa52c32be35c",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Arbitrum",
        "type": "L2 State",
        "space_id": "arbitrumfoundation.eth",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x37089188e89E990E4767798305F84b3445e9a456",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Nouns",
        "type": "Treasury DAO",
        "space_id": "nouns.eth",
        "population": 1050,
        "bills": 25,
        "health": 23.81,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x0bc3807ec262cb779b38d65b38158acc3bfede10",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "The Network State",
        "type": "Sovereign State",
        "space_id": "thenetworkstate.eth",
        "population": 1170,
        "bills": 37,
        "health": 31.62,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x639D984462dB108740156C697F4b3eE2d057a1A2",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Cabin",
        "type": "Network City",
        "space_id": "cabindao.eth",
        "population": 1050,
        "bills": 25,
        "health": 23.81,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x639D984462dB108740156C697F4b3eE2d057a1A2",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Vitalia",
        "type": "Startup City",
        "space_id": "vitalia.eth",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x0A97E36967812B41f173E6788874830113101E9E",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "CityDAO",
        "type": "Land State",
        "space_id": "citydao.eth",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x1E5dE9047b7193F161C2665Bba610b271f28b261",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "MakerDAO",
        "type": "Finance State",
        "space_id": "mkrweth.eth",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xbe8e3e38c0093c1d5c767c2f1ea2363576e7685d",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Optimism",
        "type": "L2 State",
        "space_id": "opcollective.eth",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x2501c472D5Bf54c0ca2fEe2234bdCB821ad42296",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Gitcoin",
        "type": "Public Goods",
        "space_id": "gitcoindao.eth",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x57a8865cfB10F35f9541E8d70A349263077a4497",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Lido",
        "type": "Protocol State",
        "space_id": "lido-snapshot.eth",
        "population": 1040,
        "bills": 24,
        "health": 23.08,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Curve",
        "type": "Finance State",
        "space_id": "curve.eth",
        "population": 1050,
        "bills": 25,
        "health": 23.81,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x7a16fF8270133F063aAb6C9977183D9e728353B6",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "ENS",
        "type": "Identity State",
        "space_id": "ens.eth",
        "population": 1030,
        "bills": 23,
        "health": 22.33,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xFe89cc9352E03A13C41837e559599Bf170A0f2fA",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "BanklessDAO",
        "type": "Media State",
        "space_id": "banklessvault.eth",
        "population": 1110,
        "bills": 31,
        "health": 27.93,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xf977814e90da44bfa03b6295a0616a897441acec",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Lil Nouns",
        "type": "Treasury DAO",
        "space_id": "lilnouns.eth",
        "population": 1090,
        "bills": 29,
        "health": 26.61,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xd32c3f8753a4791e2b5883850123565f128be26c",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Radicle",
        "type": "Protocol State",
        "space_id": "radicle.eth",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x8daebade922df735c38c80c7ebd708af50815faa",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Polygon",
        "type": "L2 State",
        "space_id": "polygon.eth",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x2ff3edCCA527dC3469395f879685016584282a8b",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Compound",
        "type": "Finance State",
        "space_id": "comp-vote.eth",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Decentraland",
        "type": "Metaverse State",
        "space_id": "snapshot.dcl.eth",
        "population": 1120,
        "bills": 32,
        "health": 28.57,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0x9a3f2403386227546e053f58e85c3962635e9854",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Yearn",
        "type": "Finance State",
        "space_id": "yearn.eth",
        "population": 1050,
        "bills": 25,
        "health": 23.81,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xfeb4ad2834015676239ed7f3b890a88062973711",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Synthetix",
        "type": "Finance State",
        "space_id": "snxgov.eth",
        "population": 1090,
        "bills": 29,
        "health": 26.61,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xc104f4794e77ef794e7979601d3680e6093d5084",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Gnosis",
        "type": "Protocol State",
        "space_id": "gnosis.eth",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": null,
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": null,
        "tags": [],
        "treasury_address": "0xd07c726359be2c5240c422c5448332d73315a639",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Network School",
        "type": "Geographic",
        "space_id": "ns-network-school",
        "population": 1140,
        "bills": 34,
        "health": 29.82,
        "network": null,
        "symbol": null,
        "about": "A startup society for tech founders, AI creators, and remote workers.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Singapore-Johor Special Economic Zone"
        ],
        "tags": [
            "Geographic",
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Prospera",
        "type": "Geographic",
        "space_id": "ns-prospera",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "Building a startup city on Honduras' Roatan Island.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Honduras"
        ],
        "tags": [
            "Global",
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Zuzalu",
        "type": "Hybrid",
        "space_id": "ns-zuzalu",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": "To create a pop-up city that fosters innovation and cultural exchange.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Montenegro"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Dont Die",
        "type": "Ideological",
        "space_id": "ns-dont-die",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "To defeat all causes of human and planetary death, promoting prosperity and longevity.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "USA"
        ],
        "tags": [
            "Global",
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "0ASIS",
        "type": "Ideological",
        "space_id": "ns-0asis",
        "population": 1050,
        "bills": 25,
        "health": 23.81,
        "network": null,
        "symbol": null,
        "about": "To build the first network state on Bitcoin fostering a highly aligned online community with collective action.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "4seas.io",
        "type": "Hybrid",
        "space_id": "ns-4seas-io",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "To create a crypto nomad start-up society that integrates crypto technology and innovative societal practices.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Thailand"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Afropolitan",
        "type": "Hybrid",
        "space_id": "ns-afropolitan",
        "population": 1110,
        "bills": 31,
        "health": 27.93,
        "network": null,
        "symbol": null,
        "about": "Building a pan-African digital nation.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Africa",
            "Brazil",
            "USA"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Aleph 3",
        "type": "Pop-Up City",
        "space_id": "ns-aleph-3",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": "To catalyze crypto-enabled solutions addressing economic challenges and fuel innovation in Argentina.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Argentina"
        ],
        "tags": [
            "Pop-Up City"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Aleph Citadel",
        "type": "Ideological",
        "space_id": "ns-aleph-citadel",
        "population": 1130,
        "bills": 33,
        "health": 29.2,
        "network": null,
        "symbol": null,
        "about": "To create a decentralized society and innovation hub.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Argentina"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "AnotherNation",
        "type": "Hybrid",
        "space_id": "ns-anothernation",
        "population": 1130,
        "bills": 33,
        "health": 29.2,
        "network": null,
        "symbol": null,
        "about": "To create global, unique physical spaces (embassies).",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Asgardia",
        "type": "Global",
        "space_id": "ns-asgardia",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "Establish a peaceful, independent nation in space for the benefit of all humanity.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Global"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Atlas Island",
        "type": "Hybrid",
        "space_id": "ns-atlas-island",
        "population": 1120,
        "bills": 32,
        "health": 28.57,
        "network": null,
        "symbol": null,
        "about": "To create a floating city-state that upholds individual sovereignty and the non-aggression principle.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Auravana",
        "type": "Geographic",
        "space_id": "ns-auravana",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "To design a new social system based on sustainability and resource management.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Avalon",
        "type": "Geographic",
        "space_id": "ns-avalon",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": "Foster personal development, independence, and freedom from societal constraints.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Switzerland"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Black Sky Society",
        "type": "Ideological",
        "space_id": "ns-black-sky-society",
        "population": 1170,
        "bills": 37,
        "health": 31.62,
        "network": null,
        "symbol": null,
        "about": "Hack the matrix of subquantum reality.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Bloom City",
        "type": "Pop-Up City",
        "space_id": "ns-bloom-city",
        "population": 1100,
        "bills": 30,
        "health": 27.27,
        "network": null,
        "symbol": null,
        "about": "To establish positive entertainment and organic collaboration to transform societal perceptions of aging.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "USA"
        ],
        "tags": [
            "Pop-Up City"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Blue Frontier",
        "type": "Hybrid",
        "space_id": "ns-blue-frontier",
        "population": 1130,
        "bills": 33,
        "health": 29.2,
        "network": null,
        "symbol": null,
        "about": "To build the first seastead, creating a floating city with innovative governance and sustainable living.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "French Polynesia"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "build_republic",
        "type": "Hybrid",
        "space_id": "ns-build-republic",
        "population": 1140,
        "bills": 34,
        "health": 29.82,
        "network": null,
        "symbol": null,
        "about": "Building a protocol for startup cities.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Catawba (CDEZ)",
        "type": "Geographic",
        "space_id": "ns-catawba-cdez",
        "population": 1140,
        "bills": 34,
        "health": 29.82,
        "network": null,
        "symbol": null,
        "about": "To create a regulatory framework that supports digital entrepreneurs and innovation in emerging technologies.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "USA"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "City of Atlantus",
        "type": "Virtual",
        "space_id": "ns-city-of-atlantus",
        "population": 1160,
        "bills": 36,
        "health": 31.03,
        "network": null,
        "symbol": null,
        "about": "To create a virtual and real city that integrates industry and community.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Ciudad Morazan",
        "type": "Geographic",
        "space_id": "ns-ciudad-morazan",
        "population": 1140,
        "bills": 34,
        "health": 29.82,
        "network": null,
        "symbol": null,
        "about": "To create a safe, self-sustaining, and business-friendly community that offers industrial, residential, and commercial spaces with all necessary services and amenities.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Honduras"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Closer",
        "type": "Virtual",
        "space_id": "ns-closer",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": "Pioneer the future of regenerative living through technology.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "CoCo",
        "type": "Hybrid",
        "space_id": "ns-coco",
        "population": 1040,
        "bills": 24,
        "health": 23.08,
        "network": null,
        "symbol": null,
        "about": "To create a comprehensive global co-living community for digital nomads.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Cohere",
        "type": "Geographic",
        "space_id": "ns-cohere",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": "To create a global network of coliving communities.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Antigua",
            "Ecuador",
            "Brazil",
            "Global"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "CoreNexus",
        "type": "Virtual",
        "space_id": "ns-corenexus",
        "population": 1090,
        "bills": 29,
        "health": 26.61,
        "network": null,
        "symbol": null,
        "about": "To build a decentralized 4D social operating system and gamify regenerative impact.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Cryptocity",
        "type": "Geographic",
        "space_id": "ns-cryptocity",
        "population": 1100,
        "bills": 30,
        "health": 27.27,
        "network": null,
        "symbol": null,
        "about": "To build a community of entrepreneurs using blockchain technology on Margarita Island, Venezuela.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Venezuela"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Draper Nation",
        "type": "Virtual",
        "space_id": "ns-draper-nation",
        "population": 1130,
        "bills": 33,
        "health": 29.2,
        "network": null,
        "symbol": null,
        "about": "Create a digital nation, citizen-governed, with freedom of movement and a seamless, borderless life.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Edge City",
        "type": "Pop-Up City",
        "space_id": "ns-edge-city",
        "population": 1090,
        "bills": 29,
        "health": 26.61,
        "network": null,
        "symbol": null,
        "about": "Edge City convenes people working at the frontiers of tech, science, and social innovation in popup villages across the globe.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "USA",
            "Global"
        ],
        "tags": [
            "Pop-Up City"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Eleutheria",
        "type": "Ideological",
        "space_id": "ns-eleutheria",
        "population": 1100,
        "bills": 30,
        "health": 27.27,
        "network": null,
        "symbol": null,
        "about": "Establish a free nation with limited government, free markets, and Judeo-Christian values, in Bir Tawil or by seasteading.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Egypt",
            "Sudan",
            "USA"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Embassy Network",
        "type": "Hybrid",
        "space_id": "ns-embassy-network",
        "population": 1150,
        "bills": 35,
        "health": 30.43,
        "network": null,
        "symbol": null,
        "about": "To create place-based communities experimenting with new forms of governance and solidarity.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "USA",
            "Costa Rica",
            "Spain",
            "Germany",
            "Puerto Rico",
            "Canada"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Epoch Island",
        "type": "Ideological",
        "space_id": "ns-epoch-island",
        "population": 1120,
        "bills": 32,
        "health": 28.57,
        "network": null,
        "symbol": null,
        "about": "To create a network state by 2030 that offers a decentralized, self-governing community.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Figment",
        "type": "Virtual",
        "space_id": "ns-figment",
        "population": 1070,
        "bills": 27,
        "health": 25.23,
        "network": null,
        "symbol": null,
        "about": "Building a club in the metaverse.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Singapore"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Forma City",
        "type": "Ideological",
        "space_id": "ns-forma-city",
        "population": 1100,
        "bills": 30,
        "health": 27.27,
        "network": null,
        "symbol": null,
        "about": "To build Solana Economic Zones (SEZs) around the world, bridging web3 economy with national economies.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Fractally",
        "type": "Ideological",
        "space_id": "ns-fractally",
        "population": 1090,
        "bills": 29,
        "health": 26.61,
        "network": null,
        "symbol": null,
        "about": "To create decentralized governance models and tools.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Free Gallaecia",
        "type": "Geographic",
        "space_id": "ns-free-gallaecia",
        "population": 1140,
        "bills": 34,
        "health": 29.82,
        "network": null,
        "symbol": null,
        "about": "Provide a safe, affordable, and libertarian-friendly haven in Northwest Iberia for those seeking freedom.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Spain",
            "Portugal"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "FREE Madeira",
        "type": "Geographic",
        "space_id": "ns-free-madeira",
        "population": 1120,
        "bills": 32,
        "health": 28.57,
        "network": null,
        "symbol": null,
        "about": "Promote Madeira as a hub for Bitcoin and blockchain innovation.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Portugal"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Free Republic of Verdis",
        "type": "Hybrid",
        "space_id": "ns-free-republic-of-verdis",
        "population": 1230,
        "bills": 43,
        "health": 34.96,
        "network": null,
        "symbol": null,
        "about": "To establish a sovereign state with democratic values, environmental consciousness, and ethnic reconciliation.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Croatia",
            "Serbia"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Freedom Haven",
        "type": "Ideological",
        "space_id": "ns-freedom-haven",
        "population": 1130,
        "bills": 33,
        "health": 29.2,
        "network": null,
        "symbol": null,
        "about": "Bring prosperity of free markets to liberty immigrants.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Future state",
        "type": "Virtual",
        "space_id": "ns-future-state",
        "population": 1120,
        "bills": 32,
        "health": 28.57,
        "network": null,
        "symbol": null,
        "about": "To create media and educational programs that transform futuristic concepts into practical realities, particularly in nation-building.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Gelephu Mindfulness City",
        "type": "Pop-Up City",
        "space_id": "ns-gelephu-mindfulness-city",
        "population": 1240,
        "bills": 44,
        "health": 35.48,
        "network": null,
        "symbol": null,
        "about": "Integrate economic growth with mindfulness and sustainability.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Bhutan"
        ],
        "tags": [
            "Pop-Up City"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "IlluminatedDAO",
        "type": "Virtual",
        "space_id": "ns-illuminateddao",
        "population": 1140,
        "bills": 34,
        "health": 29.82,
        "network": null,
        "symbol": null,
        "about": "To bring the power of web3 to governments.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "USA"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Immortalis",
        "type": "Ideological",
        "space_id": "ns-immortalis",
        "population": 1100,
        "bills": 30,
        "health": 27.27,
        "network": null,
        "symbol": null,
        "about": "To build a new society governed by the Prime Law.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Infinita",
        "type": "Hybrid",
        "space_id": "ns-infinita",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "To accelerate life extension technologies through a decentralized city model.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Honduras"
        ],
        "tags": [
            "Hybrid"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Internet Nation",
        "type": "Virtual",
        "space_id": "ns-internet-nation",
        "population": 1150,
        "bills": 35,
        "health": 30.43,
        "network": null,
        "symbol": null,
        "about": "To enhance the power of communities by providing tools for creation, coordination, funding, and value defense.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Ipe City",
        "type": "Pop-Up City",
        "space_id": "ns-ipe-city",
        "population": 1080,
        "bills": 28,
        "health": 25.93,
        "network": null,
        "symbol": null,
        "about": "Build network societies as a community of techno-optimists.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Brazil",
            "Global"
        ],
        "tags": [
            "Pop-Up City"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Isla de LOBOS",
        "type": "Geographic",
        "space_id": "ns-isla-de-lobos",
        "population": 1130,
        "bills": 33,
        "health": 29.2,
        "network": null,
        "symbol": null,
        "about": "To establish a decentralized and 100% sustainable community through the L.O.B.O.S. DAO.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Uruguay"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Itana by Talent Cities",
        "type": "Geographic",
        "space_id": "ns-itana-by-talent-cities",
        "population": 1220,
        "bills": 42,
        "health": 34.43,
        "network": null,
        "symbol": null,
        "about": "Building a remote-work-friendly city in Nigeria's Lekki Free Zone.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Africa",
            "Nigeria",
            "Global"
        ],
        "tags": [
            "Geographic"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Joseon",
        "type": "Virtual",
        "space_id": "ns-joseon",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": "Introduce a sovereign cyber nation with a legal framework for personal interest corporations (Denizens).",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Jur",
        "type": "Virtual",
        "space_id": "ns-jur",
        "population": 1030,
        "bills": 23,
        "health": 22.33,
        "network": null,
        "symbol": null,
        "about": "Creating an efficient jurisdiction for the digital economy.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "Global"
        ],
        "tags": [
            "Virtual"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    },
    {
        "name": "Kleros",
        "type": "Ideological",
        "space_id": "ns-kleros",
        "population": 1060,
        "bills": 26,
        "health": 24.53,
        "network": null,
        "symbol": null,
        "about": "To democratize access to justice using cutting-edge technologies.",
        "strategies": [],
        "filters": null,
        "plugins": [],
        "admins": [],
        "moderators": [],
        "members_sample": [],
        "admins_count": 0,
        "moderators_count": 0,
        "members_count": 0,
        "location": [
            "France"
        ],
        "tags": [
            "Ideological"
        ],
        "treasury_address": "Unknown",
        "latest": "Maintenance",
        "latest_proposal": {
            "id": null,
            "title": null,
            "author": null,
            "created": null,
            "start": null,
            "end": null,
            "snapshot": null,
            "state": null
        },
        "ip_addresses": null,
        "location_note": "Snapshot space data does not include IPs or geographic location."
    }
];