#!/usr/bin/env python3
"""
Crypto Market Cap History Fetcher — CoinMarketCap Historical Snapshots
=======================================================================
Scrapes coinmarketcap.com/historical/ monthly snapshots from 2013 to
today and writes crypto_history.js for the browser app.

Run:  python fetch_data.py

Requirements:
  pip install cloudscraper pandas tqdm lxml
"""

import json
import re
import sys
import time
from datetime import date, datetime
from pathlib import Path

THIS_DIR  = Path(__file__).resolve().parent
OUTPUT_JS = THIS_DIR / "crypto_history.js"

SLEEP_SEC   = 3.0   # between requests — be polite
TOP_N       = 200   # max coins to keep per snapshot

# CMC coverage starts here
START_YEAR  = 2013
START_MONTH = 5     # April 2013 only had 7 coins; May is a better start

# ── dep check ─────────────────────────────────────────────────────
def check_deps():
    missing = []
    for pkg in ("cloudscraper", "pandas", "tqdm", "lxml"):
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if missing:
        print(f"\n  pip install {' '.join(missing)}\n")
        sys.exit(1)

check_deps()

import cloudscraper
import pandas as pd
from io import StringIO
from tqdm import tqdm

scraper = cloudscraper.create_scraper(
    browser={"browser": "chrome", "platform": "windows", "mobile": False}
)

# ── helpers ───────────────────────────────────────────────────────
def parse_usd(val):
    """'$1,234,567.89' → 1234567.89  (returns 0 on failure)"""
    try:
        return float(re.sub(r"[^\d.]", "", str(val)))
    except Exception:
        return 0.0

def clean_name(raw_name, symbol):
    """'BTCBitcoin' → 'Bitcoin'"""
    s = str(raw_name).strip()
    if s.startswith(symbol):
        return s[len(symbol):].strip()
    return s

def month_dates():
    """Yield (year, month) pairs from START up to the current month."""
    today = date.today()
    y, m = START_YEAR, START_MONTH
    while (y, m) <= (today.year, today.month):
        yield y, m
        m += 1
        if m > 12:
            m = 1
            y += 1

def fetch_snapshot(year, month):
    """
    Fetches the CMC historical snapshot for the 1st of the given month.
    Returns a list of dicts: {symbol, name, market_cap, price}
    Returns None on network error (caller should retry/skip).
    """
    date_str = f"{year:04d}{month:02d}01"
    url = f"https://coinmarketcap.com/historical/{date_str}/"
    try:
        r = scraper.get(url, timeout=30)
        if r.status_code != 200:
            print(f"\n  HTTP {r.status_code} for {date_str} — skipping")
            return None
        tables = pd.read_html(StringIO(r.text))
    except Exception as e:
        print(f"\n  Failed to fetch {date_str}: {e}")
        return None

    # Find the main data table (has Symbol + Market Cap columns and >5 rows)
    df = None
    for t in tables:
        if "Symbol" in t.columns and "Market Cap" in t.columns and len(t) > 5:
            df = t
            break

    if df is None:
        return []

    rows = []
    for _, row in df.head(TOP_N).iterrows():
        sym = str(row.get("Symbol", "")).strip().upper()
        mc  = parse_usd(row.get("Market Cap", 0))
        p   = parse_usd(row.get("Price", 0))
        if not sym or mc <= 0:
            continue
        name = clean_name(row.get("Name", sym), sym)
        rows.append({"symbol": sym, "name": name, "market_cap": mc, "price": p})

    return rows

# ── Write JS (incremental) ────────────────────────────────────────
def write_js(series, names, done_months):
    """Write the JS file immediately with whatever data we have so far."""
    all_months = sorted(done_months)
    if not all_months:
        return

    # Compute pct_of_total only for completed months
    for ym in all_months:
        total = sum(
            series[sym][ym]["mc"]
            for sym in series
            if ym in series[sym]
        )
        if total > 0:
            for sym in series:
                if ym in series[sym] and "pct" not in series[sym][ym]:
                    series[sym][ym]["pct"] = round(
                        series[sym][ym]["mc"] / total * 100, 4
                    )

    coin_meta = {sym: {"name": names.get(sym, sym), "id": sym.lower()} for sym in series}

    payload = {
        "generated":   datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "start_year":  int(all_months[0][:4]) if all_months else START_YEAR,
        "dates":       [m + "-01" for m in all_months],
        "date_labels": all_months,
        "coins":       coin_meta,
        "series":      series,
    }

    js  = "// Auto-generated by fetch_data.py — do not edit manually\n"
    js += "const CRYPTO_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    OUTPUT_JS.write_text(js, encoding="utf-8")

    size_kb = OUTPUT_JS.stat().st_size / 1024
    print(f"  → {OUTPUT_JS.name} updated ({len(all_months)} months, {size_kb:.0f} KB)", flush=True)

# ── Build dataset (writes JS after every snapshot) ────────────────
def build_dataset():
    dates       = list(month_dates())
    series      = {}   # {symbol: {ym: {mc, p}}}
    names       = {}   # {symbol: name}
    done_months = []

    bar = tqdm(dates, unit="month", desc="Fetching snapshots")
    for year, month in bar:
        ym  = f"{year:04d}-{month:02d}"
        bar.set_description(ym)
        rows = fetch_snapshot(year, month)
        if rows is None:
            time.sleep(10)
            continue
        for row in rows:
            sym = row["symbol"]
            if sym not in series:
                series[sym] = {}
            series[sym][ym] = {"mc": round(row["market_cap"]), "p": round(row["price"], 8)}
            if sym not in names:
                names[sym] = row["name"]
        done_months.append(ym)
        # Write to disk after every month so the file grows in real time
        write_js(series, names, done_months)
        time.sleep(SLEEP_SEC)

    return series, names, done_months

# ── Main ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    today    = date.today()
    n_months = (today.year - START_YEAR) * 12 + (today.month - START_MONTH) + 1
    eta_min  = round(n_months * SLEEP_SEC / 60, 1)

    print("\n  Crypto Market Cap History — CMC Historical Snapshots")
    print("  ─────────────────────────────────────────────────────")
    print(f"  Fetching ~{n_months} monthly snapshots (~{eta_min} min at {SLEEP_SEC}s/req)")
    print(f"  crypto_history.js will grow in real time as each month is fetched.\n")

    series, names, done_months = build_dataset()
    if not series:
        print("\n  No data fetched. Check internet connection.\n")
        sys.exit(1)

    print(f"\n  Done! {len(done_months)} months written. Open index.html in your browser.\n")
